import React, { useState, useEffect, useRef } from 'react';
import PropTypes from 'prop-types';

// Validates the first half of an email address.
const validateText = (text) => {
  // NOTE: Passes RFC 5322 but not tested on google's standard.
  // eslint-disable-next-line no-useless-escape
  const re = /^(([^<>()\[\]\.,;:\s@\"]+(\.[^<>()\[\]\.,;:\s@\"]+)*)|(\".+\"))$/;
  return re.test(text) || text.length === 0;
};

const messages = [
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
  'Software Engine',
  'Front End Develop',
];

const useInterval = (callback, delay) => {
  const savedCallback = useRef();

  useEffect(() => {
    savedCallback.current = callback;
  }, [callback]);

  useEffect(() => {
    if (delay) {
      const id = setInterval(() => {
        savedCallback.current();
      }, delay);
      return () => clearInterval(id);
    }
    return () => {}; // pass linter
  }, [delay]);
};

const MERN = ({ loopMessage }) => {
  const hold = 50; // ticks to wait after message is complete before rendering next message
  const delay = 50; // tick length in mS

  const [idx, updateIter] = useState(0); // points to current message
  const [message, updateMessage] = useState(messages[idx]);
  const [char, updateChar] = useState(0); // points to current char
  const [isActive, setIsActive] = useState(true); // disable when all messages are printed

  useInterval(() => {
    let newIdx = idx;
    let newChar = char;
    if (char - hold >= messages[idx].length) {
      newIdx += 1;
      newChar = 0;
    }
    if (newIdx === messages.length) {
      if (loopMessage) {
        updateIter(0);
        updateChar(0);
      } else {
        setIsActive(false);
      }
    } else {
      updateMessage(messages[newIdx].slice(0, newChar));
      updateIter(newIdx);
      updateChar(newChar + 1);
    }
  }, isActive ? delay : null);

  return (
    <div
      className="inline-container"
      style={validateText(message) ? {} : { color: 'red' }}
      onMouseEnter={() => setIsActive(false)}
      onMouseLeave={() => (idx < messages.length) && setIsActive(true)}
    >
      <h3 style={{ fontSize: '18px' }}>
        <span>{message}</span>
        <span>er</span>
      </h3>
    </div>
  );
};

MERN.defaultProps = {
  loopMessage: false,
};

MERN.propTypes = {
  loopMessage: PropTypes.bool,
};

export default MERN;
